/** One intent cluster for Sand Cheats — descriptive anchors */
export const SAND_CLUSTER = {
  hub: { to: '/buy', label: 'Buy Sand Cheats (ESP & Wallhack)' },
  guides: [
    { to: '/blog/sand-esp-guide', label: 'Sand Cheats ESP guide: enemies through walls' },
    { to: '/blog/loot-esp-extraction', label: 'Sand Cheats loot ESP extraction guide' },
    { to: '/blog/sand-beginners-guide', label: 'Sand Cheats beginners guide' },
    { to: '/blog/hwid-spoofer-explained', label: 'Sand Cheats HWID spoofer explained' },
    { to: '/blog/tinybuild-anticheat-analysis', label: 'Sand Cheats anti-cheat analysis' },
    { to: '/blog/staying-updated-after-patches', label: 'Sand Cheats patch update safety guide' },
    { to: '/blog/best-sand-cheat-2026', label: 'Best Sand Cheats comparison 2026' },
    { to: '/blog/aimbot-setup-guide', label: 'Sand Cheats aim assist setup guide' },
    { to: '/blog/tinybuild-ban-waves', label: 'Sand Cheats ban waves safety guide' },
    { to: '/blog/external-cheat-architecture', label: 'How Sand Cheats external overlays work' },
    { to: '/blog/recoil-control-guide', label: 'Sand Cheats recoil control guide' },
    { to: '/blog/makima-rip-vs-sandcheats', label: 'Makima.rip vs Sand Cheats comparison' },
    { to: '/blog/zadeyo-vs-sandcheats', label: 'Zadeyo vs Sand Cheats comparison' },
    { to: '/blog/novaxware-vs-sandcheats', label: 'Novaxware vs Sand Cheats comparison' },
    { to: '/blog/sternclient-vs-sandcheats', label: 'SternClient vs Sand Cheats comparison' },
  ],
  homeAnchors: [
    { to: '/', label: 'Sand Cheats home' },
    { to: '/buy', label: 'Buy Sand Cheats — pricing and features' },
    { to: '/blog', label: 'Sand Cheats blog guides' },
    { to: '/#esp', label: 'Sand Cheats ESP feature visuals' },
    { to: '/#about-cheat', label: 'Information about Sand Cheats' },
    { to: '/#support', label: 'Sand Cheats Discord support' },
    { to: '/sitemap.xml', label: 'Sand Cheats XML sitemap' },
  ],
} as const;
